CREATE TABLE IF NOT EXISTS tb_user (
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255) NOT NULL,
    email      varchar(255) NOT NULL,
    password   varchar(255),

    CONSTRAINT tb_user_email_key UNIQUE (email),
    CONSTRAINT tb_user_pkey PRIMARY KEY (id)
    );